### PR TITLE
1.0.0

### PR DESCRIPTION
**Pull request by mitchellmanware**
Open to initiate Windows debugging

### CODE REVIEW

**Comment by mitchellmanware** [comment]
With status checks passing and win-builder version passing, this version 1.0.0 is ready for submission to CRAN after pull request completed.

**Review by sigmafelix — APPROVED** [review]
I think the package description in DESCRIPTION file could be a bit more detailed, which is the next release action item. Thank you for all of your hard work!

**Comment by mitchellmanware** [comment]
@sigmafelix I agree, and I think it is important enough for version 1.0.0 submission as the CRAN checklist asks for the description to be "as informative as possible".

I have updated the description, and I will proceed with final build and checks before submitting to CRAN soon. Thanks!

**Comment by sigmafelix** [comment]
@mitchellmanware Looks great, thanks!

**Pull request merged**
