### PR TITLE
Patch comparison test #3

### PR DESCRIPTION
**Pull request by mitchellmanware**

### CODE REVIEW

**Comment by mitchellmanware** [comment]
Fail case successful (https://github.com/NIEHS/amadeus/actions/runs/8473409463/job/23217644149)

**Comment by kyle-messier** [comment]
> Finally running for success and fail cases 🙏 Updates the `cov_current.Rout` file on the `gh-pages` branch if patch is greater or equal to current. Fails otherwise.

Awesome work and perseverance!

**Review by kyle-messier — COMMENTED** [review]
It looks like ran cases in which the expected change in R code would drop the coverage and it failed. I'm wondering if it is possible to test a case where you have corresponding testthat code for a given R script?

**Comment by mitchellmanware** [comment]
@kyle-messier 
First testthat try (https://github.com/NIEHS/amadeus/pull/56/commits/de9d6899df2c613c5dbf5b911eca73566698e21b) did not add enough lines to change the coverage, but with the placeholder and tests (https://github.com/NIEHS/amadeus/pull/56/commits/d4aca65e6bf787680a4b6726f6db936decf3ed95) the patch coverage increased as expected. The check passed and the `gh-pages/cov_current.Rout` updated to 99.07 (https://github.com/NIEHS/amadeus/blob/gh-pages/cov_current.Rout)

**Comment by mitchellmanware** [comment]
Adding
```
      - name: Overwrite cov_current.Rout
        if: ${{ github.event_name == 'push' }}
```
section and if statement now only overwrites the `gh-pages/cov_current.Rout` via push to main. Pull requests run coverage comparison without updating the file. I edited the file by hand to restore to 99.05 prior to running this newest test.

**Review by kyle-messier — APPROVED** [review]

**Pull request merged**
