### PR TITLE
1.0.7

### PR DESCRIPTION
**Pull request by mitchellmanware**

### CODE REVIEW

**Comment by mitchellmanware** [comment]
@kyle-messier Got it - I will udpate. Is that worth a resubmission?

I have also added the download badge and working on a CRAN version badge

**Comment by kyle-messier** [comment]
@mitchellmanware No, we'll undoubtedly find a whole host of things to update, so let's just wait until we have a decent collection of updates to resubmit.

**Comment by mitchellmanware** [comment]
The use of `message()` instead of `print()` in the error messages for `download_data()` changed the format of the output. Although the same message is sent to the user's console, it is not registered as the error message by `testthat::expect_error`. The expected error messages associated with `download_data()` tests (when `acknowledgement = FALSE` and `directory_to_save = NULL`) have been removed from the test. The tests still ensure the function fails when it is supposed to, but does not required a specific message.

**Comment by mitchellmanware** [comment]
Updated error handling in `download_data`, `process_covariates`, and `calc_covariates` to report error, error-generating arguments, and message using one `stop()` statement.

**Review by kyle-messier — APPROVED** [review]
1.0.6 --> 1.0.7 yes?

**Comment by mitchellmanware** [comment]
> 1.0.6 --> 1.0.7 yes?

Yes, updated to 1.0.7 for resubmission

**Pull request merged**
